export default {
    COLLISION: "COLLISION",
    EXPLOSION: "EXPLOSION",
    GAME_STATE: "GAME_STATE",
    GAME_STATE_LOCAL: "GAME_STATE_LOCAL",
    GAME_STATE_LOCAL_INIT: "GAME_STATE_LOCAL_INIT",
    GAME_STATE_LOCAL_INIT_OPPONENT: "GAME_STATE_LOCAL_INIT_OPPONENT",
    GAME_STATE_OPPONENT_LEFT_GAME: "GAME_STATE_OPPONENT_LEFT_GAME",
    GAME_STATE_LOCAL_END: "GAME_STATE_LOCAL_END",
    SHIP_SELECTION_CHANGE: "SHIP_SELECTION_CHANGE",
    PLAYER_SELECTION_READY: "PLAYER_SELECTION_READY",
    START_GAME: "START_GAME",
    JOIN_ROOM: "JOIN_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
    UPDATES: "UPDATES"
}
