module.exports = {
    DISCONNECT: "DISCONNECT",
    CONNECT: "CONNECT",
    WEB_PAGE_READY: "WEB_PAGE_READY",
    START_GAME: "START_GAME",
    GAME_STATE: "GAME_STATE",
    PLAYER_SELECTION_READY: "PLAYER_SELECTION_READY",
    JOIN_ROOM: "JOIN_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
    UPDATES: "UPDATES"
};
